---
abstract: 'The Swiss army knife for tests of Tarantool related Perl and lua code.'
author:
  - 'Anton Reznikov <a.reznikov@corp.mail.ru>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.66, CPAN::Meta::Converter version 2.120921'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Tarantool
no_index:
  directory:
    - t
    - inc
requires:
  perl: 5.006
version: 0.03
